import 'package:flutter/material.dart';

// STYLES GENERATED BY CLAUDE, TO BE UPDATED


class ModernBusinessTheme {
  static const primaryColor = Color(0xFF2C3E50);
  static const surfaceColor = Color(0xFFFFFFFF);
  static const errorColor = Color(0xFFE74C3C);


  static const List<Map<String, dynamic>> assistantColors = [
    {'color': Color(0xFF1ABC9C), 'label': 'Türkis'},
    {'color': Color(0xFF2ECC71), 'label': 'Smaragdgrün'},
    {'color': Color(0xFF3498DB), 'label': 'Hellblau'},
    {'color': Color(0xFF9B59B6), 'label': 'Violett'},
    {'color': Color(0xFFE67E22), 'label': 'Orange'},
    {'color': Color(0xFFE74C3C), 'label': 'Rot'},
    {'color': Color(0xFFF1C40F), 'label': 'Gelb'},
    {'color': Color(0xFF16A085), 'label': 'Dunkelgrün'},
    {'color': Color(0xFF2980B9), 'label': 'Marineblau'},
    {'color': Color(0xFF8E44AD), 'label': 'Lila'},
    {'color': Color(0xFFD35400), 'label': 'Dunkelorange'},
    {'color': Color(0xFFC0392B), 'label': 'Weinrot'},
    {'color': Color(0xFF7F8C8D), 'label': 'Grau'},
    {'color': Color(0xFF27AE60), 'label': 'Waldgrün'},
    {'color': Color(0xFF2C3E50), 'label': 'Dunkelblau'},
  ]; 

  static ThemeData get themeData => ThemeData(
    useMaterial3: true,
    colorScheme: ColorScheme.fromSeed(
      seedColor: primaryColor,
      brightness: Brightness.light,
    ),
    
    tabBarTheme: TabBarTheme(
      labelColor: primaryColor,
      unselectedLabelColor: Colors.grey,
      indicator: UnderlineTabIndicator(
        borderSide: BorderSide(width: 2.0, color: primaryColor),
      ),
    ),
    
    iconTheme: IconThemeData(
      color: primaryColor,
      size: 24.0,
    ),

    floatingActionButtonTheme: FloatingActionButtonThemeData(
      backgroundColor: primaryColor,
      foregroundColor: surfaceColor,
    ),
    
    dropdownMenuTheme: DropdownMenuThemeData(
      textStyle: TextStyle(color: primaryColor),
      menuStyle: MenuStyle(
        backgroundColor: WidgetStateProperty.all(surfaceColor),
      ),
    ),
    
    textTheme: TextTheme(
      titleLarge: TextStyle(
        fontSize: 24.0,
        fontWeight: FontWeight.normal,
        color: primaryColor,
      ),
      bodyLarge: TextStyle(
        fontSize: 16.0,
        color: Colors.black87,
      ),
      bodyMedium: TextStyle(
        fontSize: 14.0,
        color: Colors.black54,
      ),
    ),

  );
}


